version: "3"
services:
  gatling:
    build: ./gatling
    stdin_open: true
    tty: true
    volumes:
      - ./scenario/:/workdir/gatling-charts-highcharts-bundle-3.3.1/user-files
      - data:/workdir/gatling-charts-highcharts-bundle-3.3.1/results
    command: /bin/sh

  nginx:
    image: nginx:latest
    links:
      - gatling
    ports:
      - 8021:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - data:/var/html
    depends_on:
      - web

  web:
    build: ./golang
    restart: always
    ports:
      - 9001:9001

volumes:
  data:
    external: true